#ifndef EXT_ALLOCATORS_CONFIG_HEADER
#define EXT_ALLOCATORS_CONFIG_HEADER

#ifndef EXT_ALLOCATOR_NAMESPACE
#    define EXT_ALLOCATOR_NAMESPACE ext::allocators
#endif // EXT_ALLOCATOR_NAMESPACE
#endif // EXT_ALLOCATORS_CONFIG_HEADER
